import '../data.json';
import '../assets/media/daft_punk/daft_punk.jpg';
import "../assets/media/daft_punk/01 Daftendirekt.mp3";
import "../assets/media/daft_punk/02 WDPK 83.7 FM.mp3";
import "../assets/media/daft_punk/03 Revolution 909.mp3";
import "../assets/media/daft_punk/04 Da Funk.mp3";
import "../assets/media/daft_punk/05 Phoenix.mp3";
import "../assets/media/daft_punk/06 Fresh.mp3";
import "../assets/media/daft_punk/07 Around The World.mp3";
import "../assets/media/daft_punk/08 Rollin' & Scratchin'.mp3";
import "../assets/media/daft_punk/09 Teachers.mp3";
import "../assets/media/daft_punk/10 High Fidelity.mp3";
import "../assets/media/daft_punk/11 Rock'n Roll.mp3";
import "../assets/media/daft_punk/12 Oh Yeah.mp3";
import "../assets/media/daft_punk/13 Burnin'.mp3";
import "../assets/media/daft_punk/14 Indo Silver Club.mp3";
import "../assets/media/daft_punk/15 Alive.mp3";
import "../assets/media/daft_punk/16 Funk Ad.mp3";
import '../assets/media/radiohead/radiohead.jpg';
import "../assets/media/radiohead/01 15 Step.mp3";
import "../assets/media/radiohead/02 Bodysnatchers.mp3";
import "../assets/media/radiohead/03 Nude.mp3";
import "../assets/media/radiohead/04 Weird Fishes-Arpeggi.mp3";
import "../assets/media/radiohead/05 All I Need.mp3";
import "../assets/media/radiohead/06 Faust Arp.mp3";
import "../assets/media/radiohead/07 Reckoner.mp3";
import "../assets/media/radiohead/08 House Of Cards.mp3";
import "../assets/media/radiohead/09 Jigsaw Falling Into Place.mp3";
import "../assets/media/radiohead/10 Videotape.mp3";
import '../assets/media/out_hud/out_hud.jpg';
import "../assets/media/out_hud/01 This Just In [Intro].mp3";
import "../assets/media/out_hud/02 It's For You.mp3";
import "../assets/media/out_hud/03 One Life To Leave.mp3";
import "../assets/media/out_hud/04 Old Nude.mp3";
import "../assets/media/out_hud/05 The Song So Good They Named It Thrice.mp3";
import "../assets/media/out_hud/06 How Long.mp3";
import "../assets/media/out_hud/07 2005- A Face Odyssey.mp3";
import "../assets/media/out_hud/08 The Zillionth Watt.mp3";
import "../assets/media/out_hud/09 Dear Mr. Bush, There Are Over 100 Words For Shit And Only 1 For Music. Fuck You, Out Hud.mp3";
import "../assets/media/out_hud/10 The Stoked American.mp3";
